# Generated by Django 4.2.2 on 2023-06-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.TextField(default=5, max_length=20),
            preserve_default=False,
        ),
    ]
