# Generated by Django 4.2.2 on 2023-06-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
