# Generated by Django 4.2.2 on 2023-06-21 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuracoes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_treinos',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
